apiVersion: argoproj.io/v1alpha1    # which Argocd language we are using
kind: Application                  # the type of object Argo going to build        
metadata:
  name: postgres-infra-loader               # the name in Argocd UI
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"                 # that is where the Argocd software is installed
spec:
  project: default                  # could be different for security , but let's keep it default for now 
  source:
    chart: cloudnative-pg                           # to tell Argocd the name of the Helm Char to look for
    repoURL: https://cloudnative-pg.github.io/charts           # to give Argocd the permission to install charts from Helm , instead we do it manually , even if we did , it will   not work because of the Self-healing is "True"
    targetRevision: v0.28.0
    helm:
      valuesObject:                                           # to give Argocd the values that i want to override in the default values of the chart
        installCRDs: true
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc                   # tell Argocd which cluster , here is the same as Argocd is installed
    namespace: postgres                                  # tells Argocd which room in K8s i want cert-manager to live
  syncPolicy:
    automated:
      prune: true                                            # like a mirro , what happens in gitLab , mirrored in the cluster
      selfHeal: true                                         # if someone ignores gitLab and tried to manually change someething in this app , Argocd overwrite it to match the GitLab version
      syncOptions:
        - CreateNamespace=true                                # just in case , but i have already created it 
