apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: k8s-to-openbao
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: k8s-generated-secret
  data:
    - match:
        secretKey: service_token
        remoteRef:
          remoteKey: app/k8s-generated
          property: service_token
    - match:
        secretKey: internal_key
        remoteRef:
          remoteKey: app/k8s-generated
          property: internal_key