apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-infra-loader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/m.adham.bio-group/ikim-challenge.git
    targetRevision: main
    path: infrastructure/openbao
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true