apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-infra-loader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    # THIS MUST BE YOUR GITLAB REPO
    repoURL: https://gitlab.com/m.adham.bio-group/ikim-challenge.git
    targetRevision: main
    path: infrastructure/postgres  
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true